# Generated by Django 3.1.2 on 2020-11-14 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('subcription', '0001_initial'),
        ('subcriper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='background')),
                ('x_logo', models.CharField(default='', max_length=255, verbose_name='X_Angle_Logo')),
                ('y_logo', models.CharField(default='', max_length=255, verbose_name='Y_Angle_Logo')),
                ('h_logo', models.CharField(default='', max_length=255, verbose_name='Y_Hight_Logo')),
                ('x_txt', models.CharField(default='', max_length=255, verbose_name='X_Angle_TXT')),
                ('y_txt', models.CharField(default='', max_length=255, verbose_name='Y_Angle_TXT')),
                ('x_email', models.CharField(blank=True, default='', max_length=255, verbose_name='X_Angle_TXT')),
                ('y_email', models.CharField(blank=True, default='', max_length=255, verbose_name='Y_Angle_TXT')),
                ('x_contact', models.CharField(blank=True, default='', max_length=255, verbose_name='X_Angle_TXT')),
                ('y_contact', models.CharField(blank=True, default='', max_length=255, verbose_name='Y_Angle_TXT')),
                ('x_website', models.CharField(blank=True, default='', max_length=255, verbose_name='X_Angle_TXT')),
                ('y_website', models.CharField(blank=True, default='', max_length=255, verbose_name='Y_Angle_TXT')),
                ('font', models.CharField(default='', max_length=50)),
                ('font_thickness', models.IntegerField(default=0)),
                ('font_size', models.FloatField(default=0)),
                ('font_color', models.CharField(default='', max_length=50)),
                ('final_image', models.ImageField(blank=True, null=True, upload_to='background/final')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcription.subcription')),
            ],
        ),
        migrations.CreateModel(
            name='Planimg',
            fields=[
                ('pi_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pi_img', models.ImageField(upload_to='planimage-theme/', verbose_name='Plan Theme/Image')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], max_length=10)),
                ('background_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planimg.background')),
                ('cli_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('sbc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcriper.subcriper')),
            ],
        ),
    ]
