# Generated by Django 3.1.2 on 2020-11-14 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catimg',
            fields=[
                ('ci_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ci_img', models.ImageField(upload_to='catimg/', verbose_name='Category Image')),
                ('ci_blankimg', models.ImageField(upload_to='catblankimg/', verbose_name='Category Blank Image')),
                ('x_logo', models.CharField(max_length=255, verbose_name='X_Angle_Logo')),
                ('y_logo', models.CharField(max_length=255, verbose_name='Y_Angle_Logo')),
                ('x_txt', models.CharField(max_length=255, verbose_name='X_Angle_TXT')),
                ('y_txt', models.CharField(max_length=255, verbose_name='Y_Angle_TXT')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], max_length=10)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
