# Generated by Django 3.1.2 on 2020-11-14 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('subcription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcriper',
            fields=[
                ('sbc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.CharField(default=None, max_length=255, null=True, verbose_name='Plan Start Date')),
                ('end_date', models.CharField(default=None, max_length=255, null=True, verbose_name='Plan End Date')),
                ('image_count', models.IntegerField(blank=True, default=None, null=True, verbose_name='Total Image Remaining')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], max_length=10)),
                ('cli_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcription.subcription')),
            ],
        ),
    ]
