# Generated by Django 3.1.2 on 2020-11-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cli_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cli_fname', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='First Name')),
                ('cli_lname', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Last Name')),
                ('cli_mob', models.CharField(blank=True, default=None, max_length=20, null=True, unique=True, verbose_name='Mobile')),
                ('cli_email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('cli_pass', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Password')),
                ('com_img', models.ImageField(upload_to='companylogo/', verbose_name='Company Logo')),
                ('com_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('com_email', models.EmailField(default=None, max_length=254, null=True, verbose_name='Email')),
                ('com_mob', models.CharField(default=None, max_length=20, null=True, verbose_name='Mobile')),
                ('com_web', models.CharField(max_length=255, null=True, unique=True, verbose_name='Company Website')),
                ('com_address', models.TextField(verbose_name='Company Address')),
                ('token', models.CharField(max_length=255, verbose_name='Social Token')),
                ('type', models.CharField(max_length=255, verbose_name='Social Type')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], max_length=10)),
            ],
        ),
    ]
